name: Header Validator Lint

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/test-header-validator.yml'
      - 'header-validator/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/test-header-validator.yml'
      - 'header-validator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
        working-directory: 'header-validator'
      - run: npm run lint:check
        working-directory: 'header-validator'
