name: TypeScript Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflow/test-typescript.yml'
      - 'ts/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflow/test-typescript.yml'
      - 'ts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'ts'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint:check
